/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.egcc.app.view;

import javax.swing.JOptionPane;
import pe.egcc.app.controller.AppController;

/**
 *
 * @author CHERRES
 */
public class MCMView extends javax.swing.JInternalFrame {

    /**
     * Creates new form MCM
     */
    public MCMView() {
        initComponents();
        lblResutlado.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNumero1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNumero2 = new javax.swing.JTextField();
        btnMcm = new javax.swing.JButton();
        lblResutlado = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("MCM");

        jLabel1.setText("Numero 1:");

        jLabel2.setText("Numero 2:");

        btnMcm.setText("MCM");
        btnMcm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMcmActionPerformed(evt);
            }
        });

        lblResutlado.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblResutlado.setForeground(new java.awt.Color(0, 102, 102));
        lblResutlado.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnMcm)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblResutlado))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNumero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnMcm)
                .addGap(30, 30, 30)
                .addComponent(lblResutlado)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMcmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMcmActionPerformed
        try {
            String dato1 = txtNumero1.getText();
            String dato2 = txtNumero2.getText();
            
            if (dato1.equals("") || dato2.equals("")) {
                JOptionPane.showMessageDialog(this, "Ningún campo de texto puede estar vacío!!!",
                        "Mensaje de Error", JOptionPane.ERROR_MESSAGE);
            } else {
                int numero1 = Integer.parseInt(dato1);
                int numero2 = Integer.parseInt(dato2);
                AppController control = new AppController();
                int respuesta = control.calcularoMcm(numero1, numero2);
                lblResutlado.setText(String.valueOf(respuesta));
            }
        } catch (NumberFormatException e) {
             JOptionPane.showMessageDialog(this, "Ingrese un número correcto!","Mensaje de Error",
                    JOptionPane.ERROR_MESSAGE);
            txtNumero1.setText("");
            txtNumero2.setText("");
            lblResutlado.setText("");
        }
    }//GEN-LAST:event_btnMcmActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMcm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblResutlado;
    private javax.swing.JTextField txtNumero1;
    private javax.swing.JTextField txtNumero2;
    // End of variables declaration//GEN-END:variables
}
